# Uncomment these two line to add support for encoders to your firmware
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the following line to enable the Kyria OLED Display
# CONFIG_ZMK_DISPLAY=y

# Uncomment the following lines to enable RGB underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# deep s;eep - a to jak dziala?
# CONFIG_ZMK_SLEEP=y

# The shared configuration in my_awesome_split_board.conf is only applied when you are building with a zmk-config folder and when it is present at config/my_awesome_split_board.conf. If you are not using a zmk-config folder, you will need to include the shared configuration in both my_awesome_split_board_left.conf and my_awesome_split_board_right.conf files.
# building from zmk-config folder  https://zmk.dev/docs/development/build-flash#building-from-zmk-config-folder

# LOGGING ON
CONFIG_ZMK_USB_LOGGING=y
